language:
  - swift

os:
  - osx

osx_image:
  - xcode12.2

script:
  - xcodebuild test -project BitBay-Ticker.xcodeproj -scheme BitBay-Ticker -destination "platform=iOS Simulator,name=iPhone 12 Pro"
