language:
  - swift

os:
  - osx

osx_image:
  - xcode11.3

script:
  - xcodebuild test -project BitBay-Ticker.xcodeproj -scheme BitBay-Ticker -destination "platform=iOS Simulator,name=iPhone 11 Pro"
