language: objective-c
osx_image: xcode9.3

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild test -project BitBay-Ticker.xcodeproj -scheme BitBay-Ticker -destination "platform=iOS Simulator,name=iPhone 8"

notifications:
  email: false
