os:
  - osx

osx_image:
  - xcode10.1

before_install:
  - carthage update --platform iOS

script:
  - xcodebuild test -project BitBay-Ticker.xcodeproj -scheme BitBay-Ticker -destination "platform=iOS Simulator,name=iPhone XS"
